server:
  port: 8893
spring:
  application:
    name: user-consumer
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://root:root@127.0.0.1:8500/eureka/
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true
